name: moniepoint_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSans 
      fonts:
        - asset: fonts/dm_sans/DMSans-Regular.ttf
          weight: 400
        - asset: fonts/dm_sans/DMSans-Light.ttf
          weight: 300
        - asset: fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: fonts/dm_sans/DMSans-Semibold.ttf
          weight: 600
        - asset: fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
        